# Generated by Django 5.2 on 2026-03-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0007_alter_botruntestcasemap_metric_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybottestcases',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybottestcases',
            name='input_format',
        ),
        migrations.AddField(
            model_name='companybottestcases',
            name='input_type',
            field=models.CharField(choices=[('json', 'JSON'), ('text', 'TEXT')], default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcompanybottestcases',
            name='input_type',
            field=models.CharField(choices=[('json', 'JSON'), ('text', 'TEXT')], default='text', max_length=100),
        ),
    ]
