# Generated by Django 5.2 on 2026-03-19 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0081_alter_chatsession_session_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flow',
            name='chatbot_flo_flow_ro_f6fbff_idx',
        ),
        migrations.RemoveIndex(
            model_name='flow',
            name='chatbot_flo_hidden_55cd22_idx',
        ),
        migrations.AddField(
            model_name='flow',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company associated with this flow.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='chatbot.company'),
        ),
        migrations.AddField(
            model_name='historicalflow',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The company associated with this flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.company'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='flow_route',
            field=models.CharField(help_text='Route/path for accessing this flow.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalflow',
            name='flow_route',
            field=models.CharField(help_text='Route/path for accessing this flow.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalvoice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('flow_route', 'company')},
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['company'], name='chatbot_flo_company_df4b86_idx'),
        ),
    ]
