# Generated by Django 5.2 on 2026-03-19 06:44

from django.db import migrations

def populate_company_bot(apps, schema_editor):
    Flow = apps.get_model('chatbot', 'Flow')
    
    for flow in Flow.objects.filter(company__isnull=True):
        # Option A: Copy from bot_id (most logical default)
        flow.company = flow.bot.company
        flow.save()

def reverse_populate(apps, schema_editor):
    Flow = apps.get_model('chatbot', 'Flow')
    Flow.objects.all().update(company=None)



class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0082_remove_flow_chatbot_flo_flow_ro_f6fbff_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_company_bot, reverse_populate),
    ]
