# Generated by Django 5.2 on 2026-03-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0083_populate_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='company',
            field=models.ForeignKey(help_text='The company associated with this flow.', on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='chatbot.company'),
        ),
    ]
