# Generated by Django 5.2 on 2026-04-07 20:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0084_alter_flow_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTranslationFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('language', models.CharField(help_text="Language code (e.g., 'en', 'hi', 'kn')", max_length=10)),
                ('data', models.JSONField(help_text='Full translation JSON content')),
                ('s3_key', models.CharField(blank=True, help_text='S3 path (e.g., translations/home/en_v2.json)', max_length=500, null=True)),
                ('namespace', models.CharField(help_text="Logical group of translations (e.g., 'home', 'chat')", max_length=100)),
                ('label', models.CharField(help_text="\n        Defines a logical variant/group of translation files.\n\n        This is used to group related translations across namespaces into a single variant\n        (e.g., a specific flow experience, experiment, or release).\n\n        Examples:\n        - 'default' → base/stable translations\n        - 'mitra_guest' → guest user experience\n        - 'teacher_dashboard' → teacher-specific UI\n        - 'experiment_a' → A/B testing variant\n\n        IMPORTANT:\n        - This is NOT related to file versioning (e.g., _v1, _v2 in S3 keys).\n        - Multiple labels can exist for the same namespace and language.\n        - A label does NOT automatically apply anywhere — it is used only when mapped to a flow via \n        FlowTranslationMapping.\n        ", max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Translation File',
                'verbose_name_plural': 'historical Translation Files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TranslationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text="Language code (e.g., 'en', 'hi', 'kn')", max_length=10)),
                ('data', models.JSONField(help_text='Full translation JSON content')),
                ('s3_key', models.CharField(blank=True, help_text='S3 path (e.g., translations/home/en_v2.json)', max_length=500, null=True)),
                ('namespace', models.CharField(help_text="Logical group of translations (e.g., 'home', 'chat')", max_length=100)),
                ('label', models.CharField(help_text="\n        Defines a logical variant/group of translation files.\n\n        This is used to group related translations across namespaces into a single variant\n        (e.g., a specific flow experience, experiment, or release).\n\n        Examples:\n        - 'default' → base/stable translations\n        - 'mitra_guest' → guest user experience\n        - 'teacher_dashboard' → teacher-specific UI\n        - 'experiment_a' → A/B testing variant\n\n        IMPORTANT:\n        - This is NOT related to file versioning (e.g., _v1, _v2 in S3 keys).\n        - Multiple labels can exist for the same namespace and language.\n        - A label does NOT automatically apply anywhere — it is used only when mapped to a flow via \n        FlowTranslationMapping.\n        ", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Translation File',
                'verbose_name_plural': 'Translation Files',
                'indexes': [models.Index(fields=['namespace', 'language', 'label'], name='chatbot_tra_namespa_a117aa_idx')],
                'unique_together': {('namespace', 'language', 'label')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalFlowTranslationMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('flow', models.ForeignKey(blank=True, db_constraint=False, help_text='Flow where this translation will be used', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.flow')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('translation_file', models.ForeignKey(blank=True, db_constraint=False, help_text='Translation file to use', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.translationfile')),
            ],
            options={
                'verbose_name': 'historical Flow Translation Mapping',
                'verbose_name_plural': 'historical Flow Translation Mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FlowTranslationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(help_text='Flow where this translation will be used', on_delete=django.db.models.deletion.CASCADE, related_name='translation_mappings', to='chatbot.flow')),
                ('translation_file', models.ForeignKey(help_text='Translation file to use', on_delete=django.db.models.deletion.CASCADE, related_name='flow_usages', to='chatbot.translationfile')),
            ],
            options={
                'verbose_name': 'Flow Translation Mapping',
                'verbose_name_plural': 'Flow Translation Mappings',
                'indexes': [models.Index(fields=['flow', 'translation_file'], name='chatbot_flo_flow_id_247d77_idx')],
                'unique_together': {('flow', 'translation_file')},
            },
        ),
    ]
