# Generated by Django 5.2 on 2026-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0085_historicaltranslationfile_translationfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='ui_config',
            field=models.JSONField(blank=True, default=dict, help_text='UI level configuration like button visibility, layout toggles, etc.'),
        ),
        migrations.AddField(
            model_name='historicalflow',
            name='ui_config',
            field=models.JSONField(blank=True, default=dict, help_text='UI level configuration like button visibility, layout toggles, etc.'),
        ),
    ]
