# Generated by Django 5.2 on 2026-09-09 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0092_alter_chatsession_language_alter_story_language_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leadercategory',
            name='chatbot_lea_code_c98eae_idx',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='chatbot_rol_code_4b884d_idx',
        ),
        migrations.RemoveField(
            model_name='historicalleadercategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='code',
        ),
        migrations.RemoveField(
            model_name='leadercategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='program',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
        migrations.AddField(
            model_name='historicalleadercategory',
            name='leader_category_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicalrole',
            name='role_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='leadercategory',
            name='leader_category_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='role',
            name='role_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='program_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='leadercategory',
            index=models.Index(fields=['leader_category_uuid'], name='chatbot_lea_leader__7f9fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_uuid'], name='chatbot_rol_role_uu_dfc1ea_idx'),
        ),
    ]
