# Generated by Django 5.2 on 2026-09-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0093_remove_leadercategory_chatbot_lea_code_c98eae_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
