# Generated by Django 5.2 on 2026-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0094_alter_historicalprogram_name_alter_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatemachine',
            name='error_message',
            field=models.JSONField(blank=True, help_text='Multilingual error messages per validation key. e.g. [{"key": "required", "labels": {"en": {"text": "...", "audio_url": null}}}]', null=True),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='render_as',
            field=models.CharField(blank=True, choices=[('BUTTONS', 'Buttons'), ('DROPDOWN', 'Dropdown'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('TEXT_INPUT', 'Text Input')], help_text='How the frontend should render this question (e.g. Buttons, Dropdown).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='validate_method',
            field=models.CharField(choices=[('NONE', 'None'), ('FE', 'Frontend'), ('BE', 'Backend'), ('BOTH', 'Both')], default='NONE', help_text="Who validates the user's answer: Frontend, Backend, Both, or None.", max_length=10),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='validation_config',
            field=models.JSONField(blank=True, help_text='Type-specific validation config. e.g. {"choices": [{"key": "monthly", "label": "Monthly", "translations": {...}}], "min_choices": 1, "max_choices": 1}', null=True),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='validation_type',
            field=models.CharField(blank=True, choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date')], help_text='Type of validation to apply (e.g. Multiple Choice, Text, Number, Date).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='error_message',
            field=models.JSONField(blank=True, help_text='Multilingual error messages per validation key. e.g. [{"key": "required", "labels": {"en": {"text": "...", "audio_url": null}}}]', null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='render_as',
            field=models.CharField(blank=True, choices=[('BUTTONS', 'Buttons'), ('DROPDOWN', 'Dropdown'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('TEXT_INPUT', 'Text Input')], help_text='How the frontend should render this question (e.g. Buttons, Dropdown).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='validate_method',
            field=models.CharField(choices=[('NONE', 'None'), ('FE', 'Frontend'), ('BE', 'Backend'), ('BOTH', 'Both')], default='NONE', help_text="Who validates the user's answer: Frontend, Backend, Both, or None.", max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='validation_config',
            field=models.JSONField(blank=True, help_text='Type-specific validation config. e.g. {"choices": [{"key": "monthly", "label": "Monthly", "translations": {...}}], "min_choices": 1, "max_choices": 1}', null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='validation_type',
            field=models.CharField(blank=True, choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date')], help_text='Type of validation to apply (e.g. Multiple Choice, Text, Number, Date).', max_length=20, null=True),
        ),
    ]
