# Generated by Django 5.2 on 2026-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0095_add_validation_fields_to_companystatemachiine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystatemachine',
            name='render_as',
            field=models.CharField(blank=True, choices=[('BUTTONS', 'Buttons')], help_text='How the frontend should render this question (e.g. Buttons, Dropdown).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='validate_method',
            field=models.CharField(choices=[('NONE', 'None'), ('FE', 'Frontend')], default='NONE', help_text="Who validates the user's answer: Frontend, Backend, Both, or None.", max_length=10),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='validation_type',
            field=models.CharField(blank=True, choices=[('MULTIPLE_CHOICE', 'Multiple Choice')], help_text='Type of validation to apply (e.g. Multiple Choice, Text, Number, Date).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='render_as',
            field=models.CharField(blank=True, choices=[('BUTTONS', 'Buttons')], help_text='How the frontend should render this question (e.g. Buttons, Dropdown).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='validate_method',
            field=models.CharField(choices=[('NONE', 'None'), ('FE', 'Frontend')], default='NONE', help_text="Who validates the user's answer: Frontend, Backend, Both, or None.", max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='validation_type',
            field=models.CharField(blank=True, choices=[('MULTIPLE_CHOICE', 'Multiple Choice')], help_text='Type of validation to apply (e.g. Multiple Choice, Text, Number, Date).', max_length=20, null=True),
        ),
    ]
