# Generated by Django 5.2 on 2026-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0096_simplify_validation_enum_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatemachine',
            name='max_choices',
            field=models.IntegerField(blank=True, help_text='Maximum number of choices the user can select.', null=True),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='min_choices',
            field=models.IntegerField(blank=True, help_text='Minimum number of choices the user must select.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='max_choices',
            field=models.IntegerField(blank=True, help_text='Maximum number of choices the user can select.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='min_choices',
            field=models.IntegerField(blank=True, help_text='Minimum number of choices the user must select.', null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='validation_config',
            field=models.JSONField(blank=True, help_text='Choices list for MULTIPLE_CHOICE validation. e.g. {"choices": [{"key": "monthly", "label": "Monthly", "translations": {...}}]}', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='validation_config',
            field=models.JSONField(blank=True, help_text='Choices list for MULTIPLE_CHOICE validation. e.g. {"choices": [{"key": "monthly", "label": "Monthly", "translations": {...}}]}', null=True),
        ),
    ]
